### ISSUE TITLE
Sourcemap points to missing source files

### ISSUE THREAD

**Issue by Dinuz** [vuetifyjs/vuetify-loader#290]
I am using Nuxt 3 and integrating vuetify 3. 

Everything works smoothly but when I add sass variables customization, I get a **WARNING** _Sourcemap for "plugin-vuetify:styles/main.sass" points to missing source files_ and that keeps repeating for each component in the library. I am using the vite-plugin-vuetify to add vuetify using a nuxt.hooks.hook in an async way in modules. (I need to do this because vuetify must be loaded after vue is loaded).  Note I use the same configuration with just vue and vite and it works without warning (to be honest in this case i can load vue in the plugins).

So in nuxt.config.ts I do have the following:

```
modules: [
    async (options, nuxt) => {
      nuxt.hooks.hook('vite:extendConfig', (config) =>
        config.plugins.push(
          vuetify({
            autoImport: true,
            styles: { configFile: 'assets/styles/config.scss' },
          })
        )
      )
    },
  ],

```
The file config.scss just overwrite few sass variables. Everything works great, the variables are overwritten, the style gets applied and the components are working properly; I only get this annoying warning in the terminal, and because the warning is for every component, I do have my terminal flooded with them.

How I can prevent the warning to show up?

**Comment by Dinuz** [comment]
I noticed that the component for which the sourcemap is missing are always the same, independently from which component I am using in the app. The list is the following: 

![Screenshot 2023-01-26 at 7 59 13 PM](https://user-images.githubusercontent.com/1139472/214983778-e56bb318-5ddd-4f51-b90e-d4ebfc1e2912.png)

![Screenshot 2023-01-26 at 7 59 39 PM](https://user-images.githubusercontent.com/1139472/214983829-0f41f7b6-c2f9-4fa2-89fc-ab14f5d3f7ae.png)

![Screenshot 2023-01-26 at 8 00 00 PM](https://user-images.githubusercontent.com/1139472/214983874-6479e542-42a4-4654-ac73-e708401536f1.png)

**Comment by BayBreezy** [comment]
Hello @KaelWD , here is the reproduction: https://stackblitz.com/edit/nuxt-starter-ttbwg5?file=nuxt.config.ts
Nuxt updated to v3.1.1 and updated rollup and vite.. I think that has something to do with this warning that we are now getting. Maybe something needs to be updated in this package as well? I honestly don't know. That a look and let me know what you think please?

**Comment by Dinuz** [comment]
@BayBreezy using your config, explicitly adding

 `build: { transpile: ['vuetify'] },`

generate a failure and an error, and I cannot proceed. If I remove the instruction, the config keeps working properly but I get the warnings

**Comment by Dinuz** [comment]
@KaelWD Note that i get the following warning if I delete everything and i do a fresh npm install:

![Screenshot 2023-01-30 at 3 18 18 PM](https://user-images.githubusercontent.com/1139472/215586147-579a8441-de24-4ad8-b912-1f75a042b3ce.png)

**Comment by moni-ch** [comment]
I'm having the same issue, my settings are like @BayBreezy showed. The project works fine, but I can't remove the warnings

**Comment by Dinuz** [comment]
@KaelWD I noticed that happen a very weird thing on localhost where I amtesting.

I get in console (browser) the following error:

<img width="1433" alt="Screenshot 2023-01-31 at 6 02 15 PM" src="https://user-images.githubusercontent.com/1139472/215903630-5b86fec9-0113-4e28-a7d6-85ec7976ef90.png">

Note the structure of the url: GET http://localhost:3000/_nuxt/%EF%BF%BDplugin-vuetify:styles/main.sass

the %EF%BF%BD are typical unicode code for malformed URLs, indeed, if you remove that, the whole main.sass appears smoothly:

http://localhost:3000/_nuxt/plugin-vuetify:styles/main.sass

I think the issue is in the piece of the plugin code where it generate the url when coupled with nuxt.

**Comment by BayBreezy** [comment]
> @KaelWD I noticed that happen a very weird thing on localhost where I amtesting.
> 
> I get in console (browser) the following error:
> 
> <img alt="Screenshot 2023-01-31 at 6 02 15 PM" width="1433" src="https://user-images.githubusercontent.com/1139472/215903630-5b86fec9-0113-4e28-a7d6-85ec7976ef90.png">
> 
> Note the structure of the url: GET http://localhost:3000/_nuxt/%EF%BF%BDplugin-vuetify:styles/main.sass
> 
> the %EF%BF%BD are typical unicode code for malformed URLs, indeed, if you remove that, the whole main.sass appears smoothly:
> 
> http://localhost:3000/_nuxt/plugin-vuetify:styles/main.sass
> 
> I think the issue is in the piece of the plugin code where it generate the url when coupled with nuxt.
> 
> probably it's worth checking this [https://github.com/nuxt/nuxt/issues/15412](url)

I noticed this too.. the `%EF%BF%BD` is causing the issue with Nuxt 3. I am not sure how to go about replacing it in nuxt tho.. I think that maybe if we created a hook, we could replace it before it gets processed? Just like the Nitro hook that I created to replace it before it hits the browser(The response hook - i think).

I might have to ask Daniel which hook we can tap into to get this done.. The documentation around the hooks are not so great at the moment :(

**Comment by tux2nicolae** [comment]
I'm having a similar issue when configuring some custom scss variables

![image](https://user-images.githubusercontent.com/39991250/216842021-c9751028-abcd-45e6-a6d0-fb8ee1b6ab34.png)

**Comment by Dinuz** [comment]
@KaelWD this is the reproduction :
[https://stackblitz.com/edit/nuxt-starter-ttbwg5?file=nuxt.config.ts](url)

**Comment by JPustkuchen** [comment]
I can also confirm this issue when running `npm run dev`.

I already had
```
  build: {
    transpile: ["vuetify"],
  },
```
in place before, so that's present, but not fixing the issue.

I'm using this with nuxt3:
https://next.vuetifyjs.com/en/features/treeshaking/#treeshaking

**Comment by JPustkuchen** [comment]
Just saw that in the generated sourcecode, there's a special character preventing to load the CSS:

`_nuxt/�plugin-vuetify:styles/main.sass`
![grafik](https://user-images.githubusercontent.com/637807/217220241-8f1a2937-fe49-405e-baea-7e5b8809fcee.png)

![grafik](https://user-images.githubusercontent.com/637807/217220321-bbff3181-19ba-418e-b8b8-a866b434bb55.png)


Any ideas what may cause this?

**Comment by JPustkuchen** [comment]
I guess we can be quite sure the reason is here:
https://github.com/vuetifyjs/vuetify-loader/blob/next/packages/vite-plugin/src/stylesPlugin.ts
in the combination with _nuxt/ prefix, I guess the \0 is simply never removed!?

Could the maintainer perhaps have a short look?

And I think https://github.com/nuxt/nuxt/issues/15412 can be closed as duplicate, if we're sure this is caused in here! :)

**Comment by KaelWD** [comment]
https://vitejs.dev/guide/api-plugin.html#virtual-modules-convention

I guess nuxt is handling those wrong? With just vite the url is `/@id/__x00__plugin-vuetify:styles/main.sass`

And also probably not related to this.

**Comment by JPustkuchen** [comment]
Thanks for the quick reply @KaelWD!

This only happens with the "object" method:
```
  modules: [
    // Vuetify with automatic tree-shaking:
    // @see https://next.vuetifyjs.com/en/features/internationalization:
    // @see https://next.vuetifyjs.com/en/features/treeshaking/#treeshaking
    async (options, nuxt) => {
      nuxt.hooks.hook("vite:extendConfig", (config) =>
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        config.plugins.push(
          vuetify({
            styles: {
              configFile: "assets/style/scss/vuetifySettings.scss",
            },
          })
        )
      );
    },
```

Using
```
modules: [
    // Vuetify with automatic tree-shaking:
    // @see https://next.vuetifyjs.com/en/features/internationalization:
    // @see https://next.vuetifyjs.com/en/features/treeshaking/#treeshaking
    async (options, nuxt) => {
      nuxt.hooks.hook("vite:extendConfig", (config) =>
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        config.plugins.push(
          vuetify({
            styles: "sass"
          })
        )
      );
    },
...
```
in nuxt.config.js works with the correct paths (no special character!)

**Comment by KaelWD** [comment]
Well yeah `styles: "sass"` doesn't use virtual modules. Again, unrelated to this issue.

**Comment by Ap3rtur3** [comment]
The error still exists with `"nuxt": "^3.2.0"` and `"vuetify": "^3.1.4"`.
Has there been any progress on this issue?

**Comment by Dinuz** [comment]
@KaelWD so the issue persists, and on top of that it's impossible to get the sass variables globally in the project. In other words in the components style tag the sass variables are unknown. 
How we fix this?
The ideal solution should be to set up the vuetify plugin directly in the vite part in the nuxt.config (exactly how we do in a normal vue application), so to remove completely the async call to the nuxt.hooks in the modules, and setting up the assets in the vite preprocessorOptions. The issue is on the compilation timing.

**Comment by daniandl** [comment]
> (3) server/plugins/vuetify.fix.ts
> 
> ```
> /**
>  * Special thanks to mhfeizi for this fix - > https://github.com/mhfeizi
>  * https://github.com/nuxt/nuxt/issues/15412#issuecomment-1398110500
>  */
> export default defineNitroPlugin((nitroApp: any) => {
>   nitroApp.hooks.hook('render:response', (response: any) => {
>     response.body = response.body.replaceAll('/_nuxt/\0', '/_nuxt/')
>   })
> })
> ```
> 
> That's it! Everything works smoothly and perfectly, only thing that still need attention is that last point and the warnings.

Any chance we can avoid using `any` on here? Removing it from `nitroApp` helps but `response` doesn't receive the correct types on my end.

**Comment by QozbroQqn** [comment]
For the devs:
You probably know this already:
the problem with the malformed url come from the '\0' in the stylesPlugin.js. If you remove them, the 404 go away.

But that doesn't fix the sourcemap warnings.
To fix (hide) them you could add:
[sourcemap](https://nuxt.com/docs/api/configuration/nuxt-config/#sourcemap)

```
// nuxt.config.ts
...

sourcemap: {
  server: false,
  client: false,
},

...
```

So my nuxt.config.ts (minimalistic) looks like this:
```
export default defineNuxtConfig({
  build: {
    transpile: [ 'vuetify' ],
  },
  
  css: [
    'vuetify/styles',
    '~/assets/scss/app.scss',
  ],
  
  hooks: {
    'vite:extendConfig': (config) => {
      config.plugins?.push(vuetify({
        autoImport: true,
        styles    : { configFile: './assets/scss/vuetify.scss' },
      }));
    },
  },
  
  sourcemap: {
    server: false,
    client: false,
  },
  
  vite: {
    css    : {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "./assets/scss/settings.scss";',
        },
      },
    },
  },
});
```

The difference to @Dinuz config is:
I dont put the vuetify.scss in the vite preprocessorOptions because this would nuxt tell to load them in every component. This is not necessary imo. The css option puts them into the head once.

My vuetify.scss contains just:
```
@forward 'vuetify/settings' with (
  $color-pack: false,
  $utilities: false,
);
```

**Comment by HyunseungLee-Travis** [comment]
For me, the SASS variable didn't even work before Vuetify v3.1.2
It worked after v3.1.2
The sourcemap warning is gone now for me, using Vuetiy v3.1.5 and vite-plugin-vuetify v1.0.2
Note: using Nuxt v3

```ts
// nuxt.config.ts (minimal)

import vuetify from 'vite-plugin-vuetify'

export default defineNuxtConfig({
  // ...

  css: [  
    'vuetify/lib/styles/main.sass',
    '@mdi/font/css/materialdesignicons.min.css'
  ],

   modules: [
    (_, nuxt) => {
      nuxt.hooks.hook('vite:extendConfig', config =>
        config.plugins.push(
          vuetify({
            styles: {
              configFile: 'assets/scss/vuetify.scss'
            }
          })
        )
      )
    }
  ],
  
  sourcemap: {
    server: false,
    client: false
  },

  build: {
    transpile: ['vuetify']
  },

  // ...
})
```

```scss
$bg: var(--bg);

@use 'vuetify/settings' with (
  /* Other */
  $button-border-radius: 8,

  /* Space */
  $app-bar-padding-end: 5,
  $app-bar-padding-start: 8,
  $divider-margin : 10px,

  /* Theme Color */
  $application-background: $bg,
  $app-bar-background: $bg,
  $card-background: $bg,
  $navigation-drawer-background: $bg,
  $list-background: $bg,
  $expansion-panel-background-color: $bg,
  $overlay-scrim-background: '#3d4754',

  /* Elevation */
  $card-elevation: 0,
  $app-bar-elevation: 0
);
```

**Comment by BayBreezy** [comment]
Are there any downsides to disabling the sourcemap from the nuxt.config file? I am not sure how this sourcemap thing works.

**Comment by QozbroQqn** [comment]
Can't imagine of any. They are just source files. But I can't currently
check the docs for any hints.

BayBreezy ***@***.***> schrieb am So., 19. Feb. 2023, 04:23:

**Comment by BayBreezy** [comment]
@QozbroQqn Thank you! I will do some more digging myself. But this explanation is good. When i customize the variables and set sourcemap to false, the warnings go away.. The server plugin also removed the errors from the browser console as well.. so it would seem as though everything is working fine

**Comment by Dinuz** [comment]
@QozbroQqn I think the sourcemap solution it's the key, I looked into it and in theory it doesn't affect the results and removes the warnings.

Your solution for what regard not including vuetify into the vite preprocessor works, as long as you don't want to access the vuetify sass variables in components, if you want to do that you must include it as I did.

The increase in warmup time is normal and usual with vuetify, it happens also if you try to customize it in a plane vue application. I think it is also mentioned somewhere in the documentation.

**Comment by QozbroQqn** [comment]
@Dinuz

> I think the sourcemap solution it's the key...

Unsure if you get you right but deactivating the sourcemaps cannot be the solution. Only a workaround. I often use them to find the variables vuetify uses so I can change them without having to look trough their sass. There must be a bug inside the function which creates the base64 path to the sourcefiles. Maybe also the '\0' thing.

> Your solution for what regard not including vuetify into the vite preprocessor works, as long as you don't want to access the vuetify sass variables in components, if you want to do that you must include it as I did.

Yep you are right. I didn't read your post thoroughly enough and thought you import the whole main.scss from vuetify. I will edit my post.

> The increase in warmup time is normal and usual with vuetify...

Ah ok. Thought it might be due to the excessive warnings and what else happens.

### Another thing I encountered yesterday (maybe offtopic)

Not sure if this is caused by the vuetify-loader. Could be problem (or wanted) by vuetify itself. Vuetify imports ALL (component) sass files and three times. Even if I don't use them. Look here:

![sass_1](https://user-images.githubusercontent.com/125742475/220113650-603ca63a-72c6-404d-92d7-47856d181907.png)
![sass_2](https://user-images.githubusercontent.com/125742475/220113692-fc3584e1-b74b-4f78-bbb4-65d5ed85cb3d.png)

A quick googling revealed nothing. Maybe this is something new with latest nuxt or vuetify?

**Comment by KaelWD** [comment]
There's two things going on here, not sure if they're related. 

- Sourcemap warnings are supposed to be hidden for modules starting with `\0` (https://github.com/nuxt/nuxt/issues/14124)
- Something in nuxt is turning `/@id/__x00__plugin-vuetify:styles/main.sass` into `/_nuxt/plugin-vuetify:styles/main.sass` and then loading both

I've tried a bunch of stuff and can't get rid of either of these, I suspect it's a bug in nuxt itself because just vite works fine.

**Comment by BayBreezy** [comment]
So i discovered this morning that using webpack as your builder in nuxt3 works perfectly fine with the customised variables. I had no loading delay, I didn't have to create a server plugin, I didn't have to disable source maps. The only thing I saw was that it was unable to find the `VApp` & `VMain` components, so i got a Vue warn in the VSCode terminal. The app still worked fine and the build was fine too

**Comment by BayBreezy** [comment]
Here is a link to the hosted site: https://webpack5.behonbaker.com/
Here is the repo: https://github.com/BayBreezy/vuetify3-nuxt3-webpack5

**Comment by tabuz** [comment]
> Here is a link to the hosted site: https://webpack5.behonbaker.com/ Here is the repo: https://github.com/BayBreezy/vuetify3-nuxt3-webpack5

@BayBreezy  How would you describe difference in DX once you switched over to webpack from vite? How long does it take you to build the app?

**Comment by BayBreezy** [comment]
I will run the numbers and let you know soon (for start time)
1. I didn't have to create the server plugin to stop the errors
2. No hook was needed in the config file
3. I didn't have to restart the server every time I updated the SAAS file. 
4. I didn't have to refresh the browser for each new component that I added to the markup
5. I didn't have to disable sourcemaps in the config file

**Comment by JPustkuchen** [comment]
Still feels like a huge step backwards and should not be needed (in a better world) ;)

**Comment by tabuz** [comment]
@BayBreezy would you mind sharing this thread you mention please?

**Comment by BayBreezy** [comment]
I'm looking through the Vite issues to find it XD @tabuz

**Comment by BayBreezy** [comment]
Nuxt got updated... still no changes :(

**Comment by QozbroQqn** [comment]
I must correct myself regarding my statement about the sourcemaps and apologize for any problems that may have arisen. I had some trouble debugging my app with PhpStorm today. It always showed me the wrong line and did things the debugger didn't pointed at. I didn't notice this before because the offset was only 1 line. The reason were the disabled sourcemaps. I still do not understand why. I always thougt the debugger creates its own sourcemaps but obviously it does not.

**Comment by KareemDa** [comment]
Vuetify: `3.2.5`
Nuxt: `3.5.0` 

the problem still **EXIST!**

**Comment by metaprice** [comment]
Vuetify: 3.3.0
Nuxt: 3.5.0

Problem still there..

**Comment by freddy-daniel** [comment]
Vuetify: 3.3.0
Nuxt: 3.5.1

nuxt.config.ts
```nuxt.confi.ts
import vuetify from 'vite-plugin-vuetify';

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  ssr: false,
  modules: [
    // eslint-disable-next-line require-await
    async (_options, nuxt) => {
      // @ts-ignore
      nuxt.hooks.hook('vite:extendConfig', config => config.plugins.push(
        // vuetify()
        vuetify({
          styles: { configFile: './scss/vuetify/settings.scss' }
        })
      ));
    }
  ],
  build: {
    transpile: ['vuetify']
  },
  vite: {
    define: {
      'process.env.DEBUG': false
    },
    ssr: { // if ssr enabled in future, this config is required to load vuetify properly
      noExternal: ['vuetify']
    }
  }
});
```
Source map warning still exist! [SASS variables loading Instructions](https://vuetifyjs.com/en/features/sass-variables/) by official documentation causes this issue.

**Comment by jrutila** [comment]
Vuetify: 3.3.2
Nuxt: 3.5.2

```
import vuetify from "vite-plugin-vuetify"

export default defineNuxtConfig({
  ssr: true,
  css: [
    // "vuetify/lib/styles/main.sass",
    // "@/assets/main.scss",
    "vuetify/styles",
    "@mdi/font/css/materialdesignicons.min.css",
  ],
  build: {
    transpile: ["vuetify"],
  },
  typescript: {
    strict: false,
  },
  hooks: {
    "vite:extendConfig": (config, { isClient }) => {
      // @ts-ignore
      if (isClient) config.resolve.alias.vue = "vue/dist/vue.esm-bundler.js"

      config.plugins.push(
        vuetify({
          styles: { configFile: "assets/settings.scss" },
        })
      )
    },
  },
})
```

Still, there are Sourcemap warnings **and** the Vite client warm up is really slow.

```
Nuxi 3.5.2                                                                                                                                                                                                                                                                                                  
Nuxt 3.5.2 with Nitro 2.4.1     
                                                                                                                                                                                                                                                                            
  > Local:    http://localhost:3000/

 WARN  Sourcemap for "plugin-vuetify:styles/main.sass" points to missing source files                                                                                                                                                                                                                       
 WARN  Sourcemap for "plugin-vuetify:components/VCode/VCode.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VKbd/VKbd.sass" points to missing source files                                                                                                                                                                                                              
 WARN  Sourcemap for "plugin-vuetify:components/VApp/VApp.sass" points to missing source files                                                                                                                                                                                                              
 WARN  Sourcemap for "plugin-vuetify:components/VAppBar/VAppBar.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VAlert/VAlert.sass" points to missing source files                                                                                                                                                                                                         
 WARN  Sourcemap for "plugin-vuetify:components/VAvatar/VAvatar.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VLocaleProvider/VLocaleProvider.sass" points to missing source files                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VThemeProvider/VThemeProvider.sass" points to missing source files                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:components/VBtnToggle/VBtnToggle.sass" points to missing source files                                                                                                                                                                                                  
 WARN  Sourcemap for "plugin-vuetify:components/VParallax/VParallax.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VRadioGroup/VRadioGroup.sass" points to missing source files                                                                                                                                                                                                
 WARN  Sourcemap for "plugin-vuetify:components/VLayout/VLayoutItem.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VCheckbox/VCheckbox.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VItemGroup/VItemGroup.sass" points to missing source files                                                                                                                                                                                                  
 WARN  Sourcemap for "plugin-vuetify:components/VLayout/VLayout.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VCounter/VCounter.sass" points to missing source files                                                                                                                                                                                                      
 WARN  Sourcemap for "plugin-vuetify:components/VSelectionControlGroup/VSelectionControlGroup.sass" points to missing source files
 WARN  Sourcemap for "plugin-vuetify:components/VPagination/VPagination.sass" points to missing source files                                                                                                                                                                                                
 WARN  Sourcemap for "plugin-vuetify:components/VVirtualScroll/VVirtualScroll.sass" points to missing source files                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:components/VChipGroup/VChipGroup.sass" points to missing source files                                                                                                                                                                                                  
 WARN  Sourcemap for "plugin-vuetify:components/VLabel/VLabel.sass" points to missing source files                                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:components/VMessages/VMessages.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VImg/VImg.sass" points to missing source files                                                                                                                                                                                                              
 WARN  Sourcemap for "plugin-vuetify:components/VTabs/VTab.sass" points to missing source files                                                                                                                                                                                                             
 WARN  Sourcemap for "plugin-vuetify:components/VTooltip/VTooltip.sass" points to missing source files                                                                                                                                                                                                      
 WARN  Sourcemap for "plugin-vuetify:components/VMenu/VMenu.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VResponsive/VResponsive.sass" points to missing source files                                                                                                                                                                                                
 WARN  Sourcemap for "plugin-vuetify:components/VMain/VMain.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VFileInput/VFileInput.sass" points to missing source files                                                                                                                                                                                                  
 WARN  Sourcemap for "plugin-vuetify:components/VDivider/VDivider.sass" points to missing source files                                                                                                                                                                                                      
 WARN  Sourcemap for "plugin-vuetify:components/VSlideGroup/VSlideGroup.sass" points to missing source files                                                                                                                                                                                                
 WARN  Sourcemap for "plugin-vuetify:components/VColorPicker/VColorPicker.sass" points to missing source files                                                                                                                                                                                              
 WARN  Sourcemap for "plugin-vuetify:components/VIcon/VIcon.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VRating/VRating.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VSlider/VSlider.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VCarousel/VCarousel.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VSystemBar/VSystemBar.sass" points to missing source files                                                                                                                                                                                                   
 WARN  Sourcemap for "plugin-vuetify:components/VOverlay/VOverlay.sass" points to missing source files                                                                                                                                                                                                      
 WARN  Sourcemap for "plugin-vuetify:components/VSheet/VSheet.sass" points to missing source files                                                                                                                                                                                                           
 WARN  Sourcemap for "plugin-vuetify:components/VWindow/VWindow.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VBreadcrumbs/VBreadcrumbs.sass" points to missing source files                                                                                                                                                                                              
 WARN  Sourcemap for "plugin-vuetify:components/VTextarea/VTextarea.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VFooter/VFooter.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VTextField/VTextField.sass" points to missing source files                                                                                                                                                                                                  
 WARN  Sourcemap for "plugin-vuetify:components/VBadge/VBadge.sass" points to missing source files                                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:components/VBottomNavigation/VBottomNavigation.sass" points to missing source files
 WARN  Sourcemap for "plugin-vuetify:components/VDialog/VDialog.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VSwitch/VSwitch.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VBtnGroup/VBtnGroup.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VSelect/VSelect.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VInput/VInput.sass" points to missing source files                                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:components/VProgressCircular/VProgressCircular.sass" points to missing source files                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VAutocomplete/VAutocomplete.sass" points to missing source files                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VCombobox/VCombobox.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VSelectionControl/VSelectionControl.sass" points to missing source files                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VSnackbar/VSnackbar.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VNavigationDrawer/VNavigationDrawer.sass" points to missing source files                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VList/VList.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VTable/VTable.sass" points to missing source files                                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:components/VToolbar/VToolbar.sass" points to missing source files                                                                                                                                                                                                      
 WARN  Sourcemap for "plugin-vuetify:components/VProgressLinear/VProgressLinear.sass" points to missing source files                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VBanner/VBanner.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VExpansionPanel/VExpansionPanel.sass" points to missing source files                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VCard/VCard.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VList/VListItem.sass" points to missing source files                                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VChip/VChip.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VTimeline/VTimeline.sass" points to missing source files                                                                                                                                                                                                    
 WARN  Sourcemap for "plugin-vuetify:components/VBtn/VBtn.sass" points to missing source files                                                                                                                                                                                                              
 WARN  Sourcemap for "plugin-vuetify:components/VTabs/VTabs.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VField/VField.sass" points to missing source files                                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:components/VGrid/VGrid.sass" points to missing source files                                                                                                                                                                                                            
 WARN  Sourcemap for "plugin-vuetify:components/VColorPicker/VColorPickerCanvas.sass" points to missing source files                                                                                                                                                                                        
 WARN  Sourcemap for "plugin-vuetify:components/VColorPicker/VColorPickerEdit.sass" points to missing source files                                                                                                                                                                                          
 WARN  Sourcemap for "plugin-vuetify:directives/ripple/VRipple.sass" points to missing source files                                                                                                                                                                                                         
 WARN  Sourcemap for "plugin-vuetify:components/VSlider/VSliderTrack.sass" points to missing source files                                                                                                                                                                                                   
 WARN  Sourcemap for "plugin-vuetify:components/VSlider/VSliderThumb.sass" points to missing source files                                                                                                                                                                                                   
 WARN  Sourcemap for "plugin-vuetify:components/VColorPicker/VColorPickerSwatches.sass" points to missing source files                                                                                                                                                                                      
 WARN  Sourcemap for "plugin-vuetify:components/VColorPicker/VColorPickerPreview.sass" points to missing source files                                                                                                                                                                                       
ℹ Vite client warmed up in 42016ms                                                                                                                                                                                                                                                                          
✔ Nitro built in 25708 ms   
```

**Comment by jrutila** [comment]
Here is a reproduce repository: https://github.com/jrutila/nuxt3-vuetify3-bug

**Comment by BrianPurgert** [comment]
scss or sass whatever it is, is shit, it's just there for job security or something. It literally doesn't save anyone time. 

setting 
styles: true
just uses the precompiled css and personality I think its the move app loads faster and is less confusing. this is my config, 
https://github.com/BrianPurgert/Personal-Website/blob/main/nuxt.config.ts

**Comment by daniandl** [comment]
> 

This has nothing to do with this issue, personal opinion doesn't matter.
Please only post here if you have something useful to add for the maintainers learn from

**Comment by ElYaiko** [comment]
> 



> scss or sass whatever it is, is shit, it's just there for job security or something. It literally doesn't save anyone time.
> 
> setting styles: true just uses the precompiled css and personality I think its the move app loads faster and is less confusing. this is my config, https://github.com/BrianPurgert/Personal-Website/blob/main/nuxt.config.ts

This is the only thing I don't like from Vuetify neither, when using custom sass variables it becomes very very slow to load and even build, and we are at Nuxt 3.5.2 and this is not optimized yet :s

**Comment by David-bod** [comment]
Vuetify: 3.3.6
Nuxt: 3.6.1

Problem still there

**Comment by Talla2XLC** [comment]
@KaelWD , hello!
Can you please gice any advice on what to expect (and when) with this issue?
I am in the process of code refactoring and unfortunately leaning towards moving to another CSS framework that has normal integration with Vite (as you understand, after using Vite, I will never use Webpack in new projects)

**Comment by KaelWD** [comment]
I already said idk how to fix it: https://github.com/vuetifyjs/vuetify-loader/issues/290#issuecomment-1441362118

**Comment by Talla2XLC** [comment]
> Member

As you can understand this is just a software crutch. This is not a solution to the compilation problem.
Moreover, vuetify-loader add styles twicely when using **styles: { configFile }** props...

**Comment by KaelWD** [comment]
> just a software crutch. This is not a solution to the compilation problem

I have no idea what that means.

> vuetify-loader still add styles twicely

Nuxt does, it works fine with just vite.

**Comment by Talla2XLC** [comment]
@KaelWD ,

Do I understand correctly that you are not going to do anything to solve this issue? Neither to contact the Nuxt team, nor to edit your code for correct compilation

**Comment by cyan-berg** [comment]
@Talla2XLC if your company wants to invest some cash into Nuxt and Vuetify, this problem could probably go away haha 😆

**Comment by cyan-berg** [comment]
If you want to make requests, bring cash 😜

**Comment by Talla2XLC** [comment]
The most absurd thing here is that the problem is quite insignificant. It consists in redefining some SASS variables in Vuetify and it is obvious that the ability to set custom variables should be at the Vuetify creation stage. But no, you have to use adapters like [vuetify-loader] for Vite server with all the resulting compilation problems...

**Comment by rudolfbyker** [comment]
> The most absurd thing here is that the problem is quite insignificant. It consists in redefining some SASS variables in Vuetify and it is obvious that the ability to set custom variables should be at the Vuetify creation stage.

@Talla2XLC Would you care to make a PR against this repo or against Vuetify to fix it? It sounds like you know how.

**Comment by Talla2XLC** [comment]
@rudolfbyker , Unfortunately it will take too much time to get into this( It`s quite big framework with quite huge vuetifyCreating logic.
Temporary can be done by disabled style loading during components autoImport and then manually load all V-Elements styles sass flies using your custom variables but this is ugly approach

**Comment by AasmundN** [comment]
> Take a look at the new vuetify module for nuxt https://vuetify-nuxt-module.netlify.app/ -- I don't believe the issue is present there.

Tested it out in my repo, and it seems to be working 🔥

**Comment by Talla2XLC** [comment]
> 

Just tried this module - it`s looks like there is no treeshaking functionality implemented for Vuetify components. 
Client load all Vuetify components including JS and styles even if I don`t use them in my project:
![image](https://github.com/vuetifyjs/vuetify-loader/assets/50024798/03fae70a-e684-454b-8b3b-b3c6b1e4d18e)

**Comment by JPustkuchen** [comment]
@Talla2XLC thanks for the feedback, but I don't think it belongs here and the thread is already long enough. Could you fill an issue in the project instead, please (and eventually edit your comment with the screenshot to link it?)

Thank you :)

**Comment by vhdewald** [comment]
Since this is already a long and confusing thread, Can anyone confirm if there is any solution at all for Nuxt 3 (SSR) and Vuetify 3 working together where SASS variables could be used and overridden without issue?

**Comment by shawkiIIalasy** [comment]
Issue resolved by append `components`, `directives` for vuetify instance => '/plugins/vuetify.ts' 

<img width="773" alt="Screenshot 2023-08-04 at 3 39 34 AM" src="https://github.com/vuetifyjs/vuetify-loader/assets/37047258/06e13c16-5749-49c9-8aa1-343e67a5b9b9">

**Comment by KareemDa** [comment]
> Issue resolved by append `components`, `directives` for vuetify instance => '/plugins/vuetify.ts'
> 
> <img alt="Screenshot 2023-08-04 at 3 39 34 AM" width="773" src="https://user-images.githubusercontent.com/37047258/258266906-06e13c16-5749-49c9-8aa1-343e67a5b9b9.png">

In this way, you'll lose the Treeshaking feature

**Comment by firdauschuzaeni** [comment]
I same problem in nuxt 3 project

**Comment by linspw** [comment]
Hello everyone, everything good?
Open this [Pull Request](https://github.com/vuetifyjs/vuetify-loader/pull/313), to fix this bug, please would like more people to test the implementation.

In my tests, treeshaking worked and stopped breaking application loading.

Thank you very much in advance.

**Comment by jd-solanki** [comment]
Hey @Dinuz Does [this](https://github.com/vuetifyjs/vuetify-loader/issues/290#issuecomment-1435316938) workaround works for **nuxt 3.7** (previously it was working)? I'm now getting logs like `[nuxt] Could not resolve id plugin-vuetify:styles/main.sass` in terminal when I run nuxt 3.7 + vuetify.

Is anyone getting this with **nuxt 3.7**?

**Comment by paro-paro** [comment]
@jd-solanki 

Yeah! Getting that brand new error on nuxt 3.7.x

On latest versions...
- nuxt: 3.7.1
- vite-plugin-vuetify: 1.0.2
- vuetify: 3.3.15

You get:
- source maps warnings
- nuxt error (as pointed out by @jd-solanki)

[Reproduction repo](https://stackblitz.com/edit/nuxt-starter-uvtypj?file=package.json,app.vue)

The thing is that the vuetify-loader still "works", i.e., loads both components (on demand / treeshaked) and custom sass variables. But the styles loading is by no means DX friendly (reloading the page will result on a terrible style shift).

@KaelWD any plans on checking out these new issues? I will try to check out @linspw PR that seems to address all these problems! 

Thanks in advanced!

**Comment by ricardoaat** [comment]
Vuetify: 3.3.15
Nuxt: 3.7.1

Problem still there

Importing the settings here works when using  ```@use 'vuetify' with ``` instead of vuetify/settings, but it increases the app start up to 20 seconds.

```ts
  vite: {
    ssr: {
      noExternal: ['vuetify'],
    },
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: `@import "~/assets/vuetify/settings.scss";`,
        },
      },
    },
  },
```

**Comment by Tob0t** [comment]
I switched to` vuetify-nuxt-module` with the instructions taken from https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html#vuetify-sass-variables and it works without any error - Problem solved :)

```
export default defineNuxtConfig({
  ssr: true,
  modules: ['vuetify-nuxt-module'],
  vuetify: {
    moduleOptions: {
      /* other module options */
      styles: { configFile: '/settings.scss' }
    },
    vuetifyOptions: {
      /* vuetify options */
    }  
  },
  experimental: {
    inlineSSRStyles: false
  }
})
```

**Comment by linspw** [comment]
@Tob0t 
Apparently it's a good solution, the only negative point I saw is that this module uses a fixed version of vuetify.

Which means that you cannot separately specify a version of vuetify and it depends on the module update at first.

**Comment by paro-paro** [comment]
Hi @KaelWD 

As pointed out [here](https://github.com/nuxt/nuxt/issues/15412#issuecomment-1746429696) by the `vuetify-nuxt-module` author, the problem with the styles plugin was solved by copy/pasting the original code and making a few small changes related with the virtual prefixes. 

My question is if those changes could be applied here so we could use the plugin with no further issues in nuxt?

**Comment by ricardoaat** [comment]
Hi!

I've tried the latest version 3.3.23 with the following configuration inside nuxt.config.ts modules:
```
    async (_, nuxt) => {
      // @ts-ignore
      nuxt.hooks.hook('vite:extendConfig', (config) =>
        config.plugins.push(
          vuetify({
            autoImport: true,
            styles: { configFile: 'assets/vuetify/settings.scss' }
          })
        )
      )
    }, 
```

It works, and takes a bit longer to compile despite my settings.scss only has one font change. Still getting the warnings:

<img width="279" alt="Screenshot 2023-10-26 at 10 08 09" src="https://github.com/vuetifyjs/vuetify-loader/assets/2523576/328d5935-4ba1-404b-8b6d-8fdcc3538b88">
<img width="1481" alt="Screenshot 2023-10-26 at 10 08 29" src="https://github.com/vuetifyjs/vuetify-loader/assets/2523576/54a3beaa-899f-4df9-9fc1-d496f9612940">

**Comment by mostafaznv** [comment]
@ricardoaat just switch to [this](https://github.com/userquin/vuetify-nuxt-module) package. it works perfectly and it instantly gets updates and bugfixes.

**Comment by ricardoaat** [comment]
Thank you @mostafaznv, I will give it a try.

**Comment by Talla2XLC** [comment]
> I switched to` vuetify-nuxt-module` with the instructions taken from https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html#vuetify-sass-variables and it works without any error - Problem solved :)
> 
> ```
> export default defineNuxtConfig({
>   ssr: true,
>   modules: ['vuetify-nuxt-module'],
>   vuetify: {
>     moduleOptions: {
>       /* other module options */
>       styles: { configFile: '/settings.scss' }
>     },
>     vuetifyOptions: {
>       /* vuetify options */
>     }  
>   },
>   experimental: {
>     inlineSSRStyles: false
>   }
> })
> ```

Confirm, vuetify-nuxt-module works great.
As I understand issue was in experimental feature **inlineSSRStyles** which Nuxt uses as a default

**Comment by matteo6b** [comment]
i try install vuetify-nuxt-module  and make me the same error in console with a space in nuxt folder....

 ERROR  (node:33760) [DEP0170] DeprecationWarning: The URL virtual:nuxt:C:/Users/test/ .nuxt/paths.mjs is invalid. Future versions of Node.js will throw an error.
(Use node --trace-deprecation ... to show where the warning was created)

**Comment by speechless2** [comment]
Hello Everyone, after taking lots of my hair off i finally went to this conversation and i can confirm that the plugin 
[nuxt-vuetify-plugin]([https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html#vuetify-sass-variable](https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html#vuetify-sass-variables))

work perfectly as long as you add the piece of code from @Talla2XLC in your nuxt.config.ts.
I just tested it right now and i'm able to fully use Vuetify and change base SCSS color 

Thanks everyone

**Comment by oemer-aran** [comment]
> Hello Everyone, after taking lots of my hair off i finally went to this conversation and i can confirm that the plugin nuxt-vuetify-plugin [https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html#vuetify-sass-variable](https://vuetify-nuxt-module.netlify.app/guide/server-side-rendering.html#vuetify-sass-variables)
> 
> work perfectly as long as you add the piece of code from @Talla2XLC in your nuxt.config.ts. I just tested it right now and i'm able to fully use Vuetify and change base SCSS color
> 
> Thanks everyone

`vuetify-nuxt-module` seems to produce other issues in my advanced setup... I don't like how it does not support the default configuration options as vuetify. I have to adapt my working vuetify config so it works with this module.

Is there no better way to use SCSS variables and still have a good style loading with vuetify? It really is the biggest paint point for me with vuetify.

**Comment by daniandl** [comment]
I also have some weird issues with the community module, but I think the best course of action is to contribute to the community module. Especially since John mentioned in VueConf2023 that they are not planning on officially supporting Nuxt at the moment. Either that or parting from Vuetify... I've considered it with all these weird SSR errors

**Comment by paro-paro** [comment]
I had similar issues as @oemer-aran and I never really understood why the accepted solution was to leverage the whole nuxt-vuetify-module. 

So, by copy & pasting the stylesPlugin.ts from this repo and making a few minor changes (which is exactly what the community module does) I discovered that you can make it work with nuxt + ssr.

[public package here](https://www.npmjs.com/package/@paro-paro/vite-plugin-vuetify-sass)

[working demo here](https://stackblitz.com/edit/nuxt-vuetify-pbc3vb)

Hope it helps!

**Comment by stephenjason89** [comment]
Anyone here integrated vuetify with tailwind? 
My vuetify tailwind config uses @paro-paro package.


In my project, Vuetify is incorporated, and I use vite-plugin-vuetify for treeshaking purposes.

I've turned off Vuetify's CSS helpers and implemented Tailwind CSS.

Tailwind CSS functions perfectly except when used within a Vuetify component.

For instance, a Vuetify component like VCard is styled with `padding:0`, 

Then, trying to apply a Tailwind class such as `p-10` fails, as it gets overridden by `padding:0`.

Given that vite-plugin-vuetify creates separate CSS files for each Vuetify component, like ![image](https://github.com/nuxt-modules/tailwindcss/assets/3810177/72ba1599-bb9e-4af3-8dee-da56e02e732a), 

Specifying 'injectPosition' as 'last' doesn't solve this issue.

Upon inspecting the DOM, I noticed that the Tailwind class is indeed applied but is negated by the existing `padding:0`. 
Manually removing `padding:0` enables the Tailwind `p-10` class to function as intended.

**Comment by stephenjason89** [comment]
@BayBreezy thank you for the link, however prefix didn't do the trick for me. To increase the specificity I found that setting [`important: '#app'` in your tailwind config ](https://tailwindcss.com/docs/configuration#important) fixes it.

I hope it helps anyone having the same issue.

**Comment by BayBreezy** [comment]
@stephenjason89 No prob.
Vuetify uses the important thing on most utility classes so yeah, that makes sense

**Comment by brownsugar** [comment]
> @BayBreezy thank you for the link, however prefix didn't do the trick for me. To increase the specificity I found that setting [`important: '#__nuxt'` in your tailwind config](https://tailwindcss.com/docs/configuration#important) fixes it.
> 
> I hope it helps anyone having the same issue.

Just bumped into the same issue, although I disabled Vuetify's color packs and utilities, but Tailwinds styles always has lower priority than Vuetify components styles due to style tags' loading order, no matter set `injectPosition` or imported manually in app.vue.
![Snipaste_20231218235751248](https://github.com/vuetifyjs/vuetify-loader/assets/2935980/5a798459-b45f-4eed-b7a9-351b4a59e8a1)
![Snipaste_20231218235901318](https://github.com/vuetifyjs/vuetify-loader/assets/2935980/1051a89e-5c0d-4eaa-b75b-77df606c66be)

But the **Selector strategy** config did the trick perfectly, thanks @stephenjason89 🎉 
![Snipaste_20231219000027654](https://github.com/vuetifyjs/vuetify-loader/assets/2935980/22fbc886-647b-4518-bbbf-bbae1c5ec294)

**Comment by joao5142** [comment]
@ricardoaat  same problem here , did you find any  solution ? i'm currently working with nuxt 3.7 and vuetify 3.3 using  vite-plugin-vuetify as well

**Comment by maxflex** [comment]
The warning is still there. Vuetify 3 / Nuxt 3

**Comment by atayg** [comment]
I have same problem too. Do you have any solution?

**Comment by myextend** [comment]
Any update ?

**Comment by joao5142** [comment]
i overwrote my components creating some class with !important statement for now that be more specific than vuetify classes

**Comment by MichaelGitArt** [comment]
> I'm having a similar issue when configuring custom scss variables
> 
> ![image](https://user-images.githubusercontent.com/39991250/216842021-c9751028-abcd-45e6-a6d0-fb8ee1b6ab34.png)

Same. Only with custom scss variables (nuxt and vite plugin)

**Comment by veloz-web** [comment]
no update?

**Comment by lukasMega** [comment]
getting the same error after I upgraded from vite 5.x to 6.0.1

when I run `vitest run --coverage`

```
BEFORE:
"@vitejs/plugin-basic-ssl": "^1.1.0",
"@vitest/coverage-istanbul": "^2.1.5",
"@vitest/coverage-v8": "^2.1.5",
"vite": "^5.4.11",
"vitest": "^2.1.5",

AFTER:
"@vitejs/plugin-basic-ssl": "^1.2.0",
"@vitest/coverage-istanbul": "^2.1.6",
"@vitest/coverage-v8": "^2.1.6",
"vite": "^6.0.1",
"vitest": "^2.1.6",
```

<details>
  <summary>my vitest.config.ts:</summary>

```typescript
/// <reference types="vitest" />
import { defineConfig } from 'vitest/config';

const isCI = Boolean(process.env.CI ?? process.env.JOB_NAME) || true;

export default defineConfig({
    test: {
        dir: 'src/__tests__',
        environment: 'happy-dom',
        reporters: ['verbose', ...(isCI ? ['vitest-sonar-reporter', 'junit'] : [])],
        outputFile: {
            junit: 'test-output/junit.xml',
            'vitest-sonar-reporter': 'test-output/sonar-report.xml',
        },
        coverage: {
            enabled: false,
            provider: 'istanbul',
            reportsDirectory: 'test-output/coverage',
            reporter: ['html', 'cobertura', 'clover', 'lcov', 'text'],
            exclude: ['**/node_modules/**', '**/__tests__/**', '**/tests-e2e/**', '.eslint*'],
        },
        exclude: ['**/tests-e2e/**'],
    },
});
```

</details>

**Comment by J-Sek** [comment]
I have never seen this for the past 2 years, so maybe it got resolved by some Nuxt or Vite update.

Whenever anyone reaches this issue again, please follow these troubleshooting steps:
- generate working project using `pnpx @vuetify/cli init`
- copy configuration piece-by-piece until it starts logging these warnings
- open new issue only if you are willing to post analysis and reproduction free of AI-slop
